[package]
name = "rust-unhooking"
version = "0.1.0"
edition = "2018"
authro = "trickster0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel32-sys = "0.2.2"
winapi = {version = "0.3.9", features =["processthreadsapi","handleapi","memoryapi"]}
