[package]
name = "base64_system_enum"
version = "0.1.0"
edition = "2018"
author = "trickster0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = { git = "https://github.com/libcala/whoami" }
base64 = {version="0.13.0"}
