[package]
name = "apihooking"
version = "0.1.0"
authors = ["Idov31 <github.com/idov31>"]
edition = "2021"

[[bin]]
name = "apihooking"
path = "src/main.rs"

[dependencies]
winapi = {version = "0.3.9", features = ["winuser"]}
win32-error = "0.9.0"
detour = "0.8.1"